services:
  sols-app:
    image: gyujh630/sols-app:latest
    container_name: sols-app
    ports:
      - "8080:8080"
    depends_on:
      - sols-redis
      - sols-mysql
    restart: unless-stopped

  sols-redis:
    image: redis:latest
    container_name: sols-redis
    hostname: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  sols-mysql:
    image: mysql:latest
    container_name: sols-mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
