version: '3.8'

services:
  sols-app:
    image: gyujh630/sols-app:latest
    container_name: sols-app
    ports:
      - "8080:8080"
    depends_on:
      - sols-redis
      - sols-mysql
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    networks:
      - sols-network

  sols-redis:
    image: redis:latest
    container_name: sols-redis
    hostname: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - sols-network

  sols-mysql:
    image: mysql:latest
    container_name: sols-mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - sols-network

volumes:
  mysql_data:

networks:
  sols-network:
    driver: bridge
