version: '3'

services:
  sols-app:
    image: gyujh630/sols-app:latest
    container_name: sols-app
    ports:
      - "8080:8080"
    depends_on:
      - sols-redis
    environment:
      TZ: "Asia/Seoul"

  sols-redis:
    image: redis:latest
    container_name: sols-redis
    hostname: redis
    ports:
      - "6379:6379"