spring:
  profiles:
    include: oauth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      port: 6379
  servlet:
    multipart:
      file-size-threshold: 2MB
      location: /tmp/s3
      max-file-size: 5MB
      max-request-size: 10MB
  jackson:
    property-naming-strategy: SNAKE_CASE
cloud:
  aws:
    s3:
      bucket: solslab
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

logging.level:
  org.springframework.boot.autoconfigure: ERROR
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT}
    client-secret: ${KAKAO_SECRET}
#    redirect-uri: ${ENDPOINT}/auth/kakao/callback
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me

